# Write your code here!
game_hash = {
  :home => {
    :team_name => 'Brooklyn Nets',
    :colors => ["Black", "White"],
    :players => [{
      :player_name => nil,
      :number => nil,
      :shoe => nil,
      :points => nil,
      :rebounds => nil,
      :assists => nil,
      :steals => nil,
      :blocks => nil,
      :slam_dunks => nil,
      },
      {
        :player_name => nil,
        :number => nil,
        :shoe => nil,
        :points => nil,
        :rebounds => nil,
        :assists => nil,
        :steals => nil,
        :blocks => nil,
        :slam_dunks => nil,
        },
        {
          :player_name => nil,
          :number => nil,
          :shoe => nil,
          :points => nil,
          :rebounds => nil,
          :assists => nil,
          :steals => nil,
          :blocks => nil,
          :slam_dunks => nil,
        },
          {
            :player_name => nil,
            :number => nil,
            :shoe => nil,
            :points => nil,
            :rebounds => nil,
            :assists => nil,
            :steals => nil,
            :blocks => nil,
            :slam_dunks => nil,
          },
            {
              :player_name => nil,
              :number => nil,
              :shoe => nil,
              :points => nil,
              :rebounds => nil,
              :assists => nil,
              :steals => nil,
              :blocks => nil,
              :slam_dunks => nil,
              }]
  },
  :away => {
    :team_name => 'Charlotte Hornets',
    :colors => ["Turquoise", "Purple"],
    :players => [{
      :player_name => nil,
      :number => nil,
      :shoe => nil,
      :points => nil,
      :rebounds => nil,
      :assists => nil,
      :steals => nil,
      :blocks => nil,
      :slam_dunks => nil,
      },
      {
        :player_name => nil,
        :number => nil,
        :shoe => nil,
        :points => nil,
        :rebounds => nil,
        :assists => nil,
        :steals => nil,
        :blocks => nil,
        :slam_dunks => nil,
        },
        {
          :player_name => nil,
          :number => nil,
          :shoe => nil,
          :points => nil,
          :rebounds => nil,
          :assists => nil,
          :steals => nil,
          :blocks => nil,
          :slam_dunks => nil,
        },
          {
            :player_name => nil,
            :number => nil,
            :shoe => nil,
            :points => nil,
            :rebounds => nil,
            :assists => nil,
            :steals => nil,
            :blocks => nil,
            :slam_dunks => nil,
          },
            {
              :player_name => nil,
              :number => nil,
              :shoe => nil,
              :points => nil,
              :rebounds => nil,
              :assists => nil,
              :steals => nil,
              :blocks => nil,
              :slam_dunks => nil,
              }]
  }
}

puts game_hash.class
puts game_hash

